# Generated by Django 5.1.1 on 2024-10-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='keywords_list',
        ),
        migrations.AlterField(
            model_name='scheme',
            name='ministry',
            field=models.CharField(max_length=200),
        ),
    ]
