# Generated by Django 5.1.1 on 2024-10-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
    ]
