# Generated by Django 5.1.1 on 2024-10-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_remove_userprofile_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'frontend_userprofile',
                'managed': False,
            },
        ),
    ]
