# Generated by Django 5.1.1 on 2024-10-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_phoneaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='scheme_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='scheme_link',
            field=models.URLField(default='http://example.com'),
        ),
    ]
