# Generated by Django 5.1.1 on 2024-10-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_scheme_scheme_image_scheme_scheme_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='scheme_link',
            field=models.CharField(default='http://example.com', max_length=200),
        ),
    ]
