# Generated by Django 5.1.1 on 2024-10-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_scheme_scheme_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='ministry',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_image',
            field=models.ImageField(blank=True, null=True, upload_to='scheme_images/'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_link',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_name',
            field=models.CharField(max_length=255),
        ),
    ]
