# Generated by Django 5.1.1 on 2024-10-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_scheme_ministry_alter_scheme_scheme_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='scheme_summary',
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_image',
            field=models.ImageField(default='ConnectPy\\static\\images\\products\x0c1.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_link',
            field=models.URLField(),
        ),
    ]
