# Generated by Django 5.1.1 on 2024-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_remove_scheme_scheme_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='scheme_image',
            field=models.ImageField(default='ConnectPy\\static\\images\\products\\f1.png', upload_to='images/'),
        ),
    ]
