# Generated by Django 5.1.1 on 2024-10-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_scheme_scheme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='scheme_summary',
            field=models.CharField(default='No Data Avilable', max_length=1000),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='ministry',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_link',
            field=models.CharField(default='http://example.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_name',
            field=models.CharField(max_length=200),
        ),
    ]
