# Generated by Django 5.1.1 on 2024-10-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
