# Generated by Django 5.1.1 on 2024-10-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_delete_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='ministry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_image',
            field=models.ImageField(blank=True, null=True, upload_to='schemes/'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_summary',
            field=models.TextField(),
        ),
    ]
