# Generated by Django 5.1.1 on 2024-10-25 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_alter_product_brand_name_alter_product_product_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_summary',
            field=models.CharField(default='No Data Available', max_length=1000),
        ),
    ]
